name: 更新市场信号报告

on:
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 安装依赖
      run: npm install

    - name: 运行市场信号分析器
      run: node app.js

    - name: 更新 README 与报告
      run: |
        # 创建 README 标题
        echo "# 比特币市场信号报告" > README.md
        echo "" >> README.md
        echo "最后更新时间: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> README.md
        echo "" >> README.md

        # 将 report.txt 内容转换为 markdown 格式
        sed 's/【\(.*\)】/## \1/' report.txt | sed 's/^[^#].*[^[:space:]]/- &/' >> README.md

    - name: 提交并推送更改
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "更新市场信号报告" || exit 0
        git push