name: Update Market Signal Report

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run market signal analyzer
      run: node app.js

    - name: Update README with report
      run: |
        # Read the report.json and format it as a table
        echo "# Bitcoin Market Signal Report" > README.md
        echo "" >> README.md
        echo "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> README.md
        echo "" >> README.md
        echo "## Market Signals" >> README.md
        echo "" >> README.md
        
        # Extract and format data from report.json
        echo "### Fear & Greed Index" >> README.md
        echo "- Value: $(jq -r '.fearGreed.value' report.json)" >> README.md
        echo "- Classification: $(jq -r '.fearGreed.classification' report.json)" >> README.md
        echo "" >> README.md
        
        echo "### Technical Indicators" >> README.md
        echo "- Price: $$(jq -r '.technical.price' report.json)" >> README.md
        echo "- RSI: $(jq -r '.technical.rsi' report.json)" >> README.md
        echo "- MACD Trend: $(jq -r '.technical.macd.trend' report.json)" >> README.md
        echo "- Volume: $$(jq -r '.technical.volume' report.json)" >> README.md
        echo "" >> README.md
        
        echo "### Market Evaluation" >> README.md
        echo "- Score: $(jq -r '.evaluation.score' report.json)" >> README.md
        echo "- Suggestion: $(jq -r '.evaluation.suggestion' report.json)" >> README.md
        echo "" >> README.md
        
        echo "### Signals" >> README.md
        jq -r '.evaluation.signals[]' report.json | while read -r signal; do
          echo "- $signal" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update market signal report" || exit 0
        git push 